CREATE TABLE ctakes_annotated_docs_dummy(title STRING, PARSED BOOLEAN, text STRING, annotations STRING) PARTITIONED BY (loaded STRING) STORED AS SEQUENCEFILE;
CREATE TABLE ctakes_annotated_docs(title STRING, PARSED BOOLEAN, text STRING, annotations STRING) PARTITIONED BY (loaded STRING) STORED AS SEQUENCEFILE;
CREATE TABLE ctakes_annotated_docs_tmp(title STRING, PARSED BOOLEAN, text STRING, annotations STRING) PARTITIONED BY (loaded STRING) STORED AS SEQUENCEFILE;
